#!  /usr/bin/python

from scapy.all import *
import sys
import socket
def udp(hostname):
	for i in range(1, 28):
	    pkt = IP(dst=hostname, ttl=i) / UDP(dport=33434)
	    reply = sr1(pkt, verbose=0)
	    if reply is None:
		break
	    elif reply.type == 3:
		try:
			host = socket.gethostbyaddr(reply.src)
			print i," => ",reply.src,"(",host[0],")"
		except :
			print i," => ",reply.src
		print "Done!"
		break
	    else:
		try:
			host = socket.gethostbyaddr(reply.src)
			print i," => ",reply.src,"(",host[0],")"
		except :
			print i," => ",reply.src

if(os.getuid() != 0):
	print "Access denied"
	exit()

if(len(sys.argv) != 3):
	print "Usage : traceroute <type> <target>"
	exit()

if(sys.argv[1] == "udp"):
	udp(sys.argv[2])
else:
	print "------------------ Type List ------------------"
	print "   udp "
	print "-----------------------------------------------"
